# local path
lmd_dir: '/home/salu133445/NAS/salu133445/midinet/lmd/'
lpd_dir: '/home/salu133445/NAS/salu133445/midinet/lpd/'

# parameters
dataset: 'full' # 'matched'
beat_resolution: 24
multicore: 30
