# local path
dataset_path: '/home/salu133445/NAS/salu133445/midinet/lmd/lmd_full/'
result_path: '/home/salu133445/NAS/salu133445/midinet/lpd/lpd_full'

# parameters
beat_resolution: 24
multicores: 40
link_to_msd: False
