# local path
dataset_path: '/home/salu133445/NAS/RichardYang/Dataset/Lakh_MIDI_Dataset/lmd_full/'
result_path: '/home/salu133445/NAS/salu133445/midinet/lpd/'
score_file_path: '/home/salu133445/NAS/RichardYang/Dataset/Lakh_MIDI_Dataset/match_scores.json'

# parameters
beat_resolution: 24
multicores: 40
link_to_msd: False
